"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/Footer";
import NextAuthSessionProvider from "@/Providers/NextAuthSessionProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body className="bg-gray-50">
          <Navbar />
          <SessionProvider >
            <main className="pt-16 text-black">{children}</main> {/* pt-16 to avoid navbar overlap */}
          </SessionProvider>
          <Footer></Footer>
        </body>
        <ToastContainer></ToastContainer>
      </NextAuthSessionProvider>
    </html>
  );
}
